# fly-backup.toml - Separate app configuration for backup service
# This runs as a scheduled task to backup the database

app = "booklib-backup"
primary_region = "sjc"

[build]

[mounts]
  source = "booklib_data"
  destination = "/data"

  [[mounts]]
  source = "booklib_backup"
  destination = "/backup"
  initial_size = "3gb"

[env]
  DATABASE_PATH = "/data/booklib.db"

# This won't be a web service, just a scheduled task
